/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ismartv_sakura_core_HttpDownload */

#ifndef _Included_cn_ismartv_sakura_core_HttpDownload
#define _Included_cn_ismartv_sakura_core_HttpDownload
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ismartv_sakura_core_HttpDownload
 * Method:    downloadForSingleThread
 * Signature: (Ljava/util/Map;)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_cn_ismartv_sakura_core_HttpDownload_downloadForSingleThread
  (JNIEnv * env, jobject thiz, jobject object)
  {

        return 0;
  }

/*
 * Class:     cn_ismartv_sakura_core_HttpDownload
 * Method:    multiDownloadForSingleThread
 * Signature: (Ljava/util/List;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_cn_ismartv_sakura_core_HttpDownload_multiDownloadForSingleThread
   (JNIEnv * env, jobject thiz, jobject object)
  {

        return 0;
  }

#ifdef __cplusplus
}
#endif
#endif
